<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Prabhukrishnan" name="testcases.CIB.PreLogin_Login.TC28_CIB_Login_WithValidOTP_Login" tests="1" failures="0" timestamp="19 Nov 2020 20:05:21 GMT" time="58.759" errors="1">
  <testcase name="CIB_ForgotPassword_InvalidInput_Check" time="58.759" classname="testcases.CIB.PreLogin_Login.TC28_CIB_Login_WithValidOTP_Login">
    <error type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
	at utils.Reporter.reportStep(Reporter.java:29)
	at wrappers.GenericWrappers.clickWrapper(GenericWrappers.java:335)
	at wrappers.GenericWrappers.clickByXpath(GenericWrappers.java:719)
	at pages.CIBPreLoginPage.click2FAdropdownBtn(CIBPreLoginPage.java:127)
	at testcases.CIB.PreLogin_Login.TC28_CIB_Login_WithValidOTP_Login.CIB_ForgotPassword_InvalidInput_Check(TC28_CIB_Login_WithValidOTP_Login.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- CIB_ForgotPassword_InvalidInput_Check -->
</testsuite> <!-- testcases.CIB.PreLogin_Login.TC28_CIB_Login_WithValidOTP_Login -->
